### ISSUE TITLE
### EPIC (Frontend structure)

### ISSUE THREAD

**Issue by Ricard-Garcia** [Ricard-Garcia/mvst-coding-challenge#15]
- [x] Create main styles #5
- [x] Create frontend directories #6
- [x] Design main components #7
- [x] Add theme functionality #14
- [ ] Add timer components & functionality #14
